### PR TITLE
ECDC-2300: replace Bintray

### PR DESCRIPTION
**Pull request by amues**
Update Conan package versions

### CODE REVIEW

**Comment by amues** [comment]
@mortenjc, @dorotheapfeiffer, can we merge this into master?

**Comment by mortenjc** [comment]
I don't have an opinion on that so I'll leave that up to Doro

**Comment by dorotheapfeiffer** [comment]
The change is fine with me. Do you have any idea why the newest H5CPP version did cause problems? I mean, you rolled back to an earlier one..

**Review by dorotheapfeiffer — COMMENTED** [review]
Good!

**Review by dorotheapfeiffer — APPROVED** [review]
Which version of h5cpp did not work?

**Comment by amues** [comment]
Hi @dorotheapfeiffer, thank you for the review. The h5cpp version that didn't work was h5cpp/0.4.0@ess-dmsc/stable. From the build errors you sent in the email, it seems that the issue (or at least part of it) was the namespace identifiers `fs` and `boost` being undefined.

The h5cpp file _src/h5cpp/core/filesystem.hpp_ includes the following changes in version 0.4.0:
```
#ifdef WITH_BOOST
#include <boost/filesystem.hpp>
namespace fs = boost::filesystem;
#else

...

#if INCLUDE_STD_FILESYSTEM_EXPERIMENTAL
// Include it
#include <experimental/filesystem>
namespace fs = std::experimental::filesystem;

// We have a decent compiler and can use the normal version
#else
// Include it
#include <filesystem>
namespace fs = std::filesystem;
#endif
```
What compiler version did you use for that build attempt?

**Pull request merged**
